site_name: Motlow State - Technical Operations Documentation
nav:
    - Home: index.md
    - FAQ:
        - Can IT work on my personal device?: can-it-work-on-my-personal-device.md
    - Email:
        - How can I disable focused inbox?: how-can-i-disable-focused-inbox.md
        - I received an encrypted message, how do I open this?: i-received-an-encrypted-message-how-do-i-open-this.md
theme: flatly
markdown_extensions:
    - toc
    - admonition
    - def_list